Ext.define('OzShorebirdsV2.store.Species', {
    extend: 'Ext.data.Store',
           
    config: {
        model: 'OzShorebirdsV2.model.Species',
		sorters: 'speciesLast',
        grouper : function(record) {
			return record.get('speciesLast');
        },
        data: [
			{speciesCommon: 'Asian Dowitcher',
				speciesFirst: 'Asian',
				speciesLast: 'Dowitcher',
				speciesScientific: 'Limnodromus semipalmatus',
				speciesImage: 'asiandowitcher',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Black straight bulbous-tipped bill, half the size of Bar-tailed Godwit. Scapulars with very dark centres forming a streaky appearance in upperparts, more truncated rear end than Godwits, white underwing. Feeding behaviour distinctive, with "sewing machine like" action with repeated deep probes.',
				speciesInflight: 'Legs extending well beyond the tail.',
				speciesSize: '34'}, 
			{speciesCommon: 'Australian Painted Snipe',
				speciesFirst: 'Australian',
				speciesLast: 'Painted Snipe',
				speciesScientific: 'Rostratula australis',
				speciesImage: 'australianpaintedsnipe',
				speciesHabitat: 'Shallow freshwater swamps, lethargic during the day while resting, becoming more active towards dusk.',
				speciesStatus: 'Resident Species',
				speciesTip: 'White collar extending down to back in two cream lines, white chest. Females have dark brown neck with wings and back bronzy grey-green. Males are greyer with banded pattern of creamy spots on wings. Immature similar to male.',
				speciesInflight: 'N\/A',
				speciesSize: '27'},
			{speciesCommon: 'Australian Pied Oystercatcher',
				speciesFirst: 'Australian',
				speciesLast: 'Oystercatcher',
				speciesScientific: 'Haematopus longirostris',
				speciesImage: 'australianpiedoystercatcher',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Distinctive black and white plumage with red bill, red legs. Stocky appearance. Could be confused with South Island Pied Oystercatcher - a rare visitor which has shorter legs, longer thinner bill and more extensive white underwings in flight.',
				speciesInflight: 'N\/A',
				speciesSize: '46'},
			{speciesCommon: 'Australian Pratincole',
				speciesFirst: 'Australian',
				speciesLast: 'Pratincole',
				speciesScientific: 'Stiltia isabella',
				speciesImage: 'australianpratincole',
				speciesHabitat: 'Loose flocks on open grasslands and gibber plains of the arid interior.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Smaller, slimmer, stand more erect, and longer legged than Oriental Pratincoles, also. At rest wing primaries extend well past end of tail.',
				speciesInflight: 'Feet project beyond the end of the tail in Australian Pratincole.',
				speciesSize: '21'},
			{speciesCommon: 'Banded Lapwing',
				speciesFirst: 'Banded',
				speciesLast: 'Lapwing',
				speciesScientific: 'Vanellus tricolor',
				speciesImage: 'bandedlapwing',
				speciesHabitat: 'Open short grasslands and semi-arid rangelands, souhtern half of Australia.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Small bright red wattle and bold, U-shaped breast distinguishes it from Masked Lapwing.',
				speciesInflight: 'N\/A',
				speciesSize: '27'},
			{speciesCommon: 'Banded Stilt',
				speciesFirst: 'Banded',
				speciesLast: 'Stilt',
				speciesScientific: 'Cladorhynchus leucocephalus',
				speciesImage: 'bandedstilt',
				speciesHabitat: 'Large dense flocks on saline lakes and saltpans, less commonly on freshwater marshes.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Chestnut, U-shaped band across lower breast which merges into black patch at the centre of the belly.<\/p><br \/><p>Non-breeding plumage varies greatly, but breast band narrower and duller, can be reduced to brown smudges on upper belly.<\/p><br \/><p>Juveniles lack breast band so underparts are wholly white - can be confused with juvenile Black-winged Stilt - see above.',
				speciesInflight: 'N\/A',
				speciesSize: '39'}, 
			{speciesCommon: 'Bar-tailed Godwit',
				speciesFirst: 'Bar-tailed',
				speciesLast: 'Godwit',
				speciesScientific: 'Limosa lapponica',
				speciesImage: 'bartailedgodwit',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Bill usually appears slightly upturned, bicoloured (pink and black). In non-breeding plumage upperparts and neck are streaky, striped, and scalloped. Legs black. Immature birds more heavily streaked.',
				speciesInflight: 'Streaky appearance with barred tail, and plain belly in complete non-breeding plumage.',
				speciesSize: '39'},
			{speciesCommon: 'Beach Stone-curlew',
				speciesFirst: 'Beach',
				speciesLast: 'Stone-curlew',
				speciesScientific: 'Esacus magnirostris',
				speciesImage: 'beachstonecurlew',
				speciesHabitat: 'Beaches, mudflats, small islands and reefs of northern and eastern Australia.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Large, extremely heavy bill, less streaky plumage than Bush Stone-curlew. Primarily nocturnal but will change activity somewhat based on tides.',
				speciesInflight: 'N\/A',
				speciesSize: '55'}, 
			{speciesCommon: 'Black-fronted Dotterel',
				speciesFirst: 'Black-fronted',
				speciesLast: 'Dotterel',
				speciesScientific: 'Elseyornis melanops',
				speciesImage: 'blackfronteddotterel',
				speciesHabitat: 'Pairs or small family groups on dry margins of freshwater wetlands, large or small.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Red bill and eye ring with black eye mask and black chest band.',
				speciesInflight: 'N\/A',
				speciesSize: '17'},
			{speciesCommon: 'Black-tailed Godwit',
				speciesFirst: 'Blac-tailed',
				speciesLast: 'Godwit',
				speciesScientific: 'Limosa limosa',
				speciesImage: 'blacktailedgodwit',
				speciesHabitat: 'Coastal mudflats and sandy intertidalzones, also inland saline and freshwater marshes',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Bill generally straight and less bi-coloured compared to Bar-tailed Godwit bill. Overall size is smaller with a more delicate skinnier appearance, upper parts and neck are generally uniformly matt grey in non-breeding plumage. White spot near eye above bill will often be the only place of notable contrast on the bird.',
				speciesInflight: 'Black end of tail contrasts with white rump, also obvious wide wing-bars on upper wing. Legs extend further beyond tail compared to Bar-tailed Godwit.',
				speciesSize: '39'},
			{speciesCommon: 'Black-winged Stilt',
				speciesFirst: 'Black-winged',
				speciesLast: 'Stilt',
				speciesScientific: 'Himantopus himantopus',
				speciesImage: 'blackwingedstilt',
				speciesHabitat: 'Wide variety of inland saline and freshwater wetlands, also coastal intertidal zones.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Black and white, thin straight needle-like bill and very long pink, thin legs. Adults with black on back of neck, but juveniles lack this and appear similar to juvenile Banded Stilts. Juvenile Black-winged Stilts have a dirty looking head, and at rest the upper parts are scaly brown to black.',
				speciesInflight: 'Juvenile Black-winged Stilts have a white rump patch extends well up the back, whereas juvenile Banded Stilts have a clean white head, and large white patch in the middle of the back that extends from the white neck.',
				speciesSize: '37'},
			{speciesCommon: 'Broad-billed Sandpiper',
				speciesFirst: 'Broad-billed',
				speciesLast: 'Sandpiper',
				speciesScientific: 'Limicola falcinellus',
				speciesImage: 'broadbilledsandpiper',
				speciesHabitat: 'Coastal intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Longish bill that droops right at the end, bigger and browner than a Red-necked Stint. Split supercilium good characteristic but not always obvious, also legs might show a yellowish tinge which if seen would not occur in Red-necked Stint or Curlew Sandpiper (both have black legs). Compact rear-end.',
				speciesInflight: 'N\/A',
				speciesSize: '17'}, 
			{speciesCommon: 'Bush Stone-curlew',
				speciesFirst: 'Bush',
				speciesLast: 'Stone-curlew',
				speciesScientific: 'Burhinus grallarius',
				speciesImage: 'bushstonecurlew',
				speciesHabitat: 'Nocturnal, northern and north-eastern woodlands, declining in south.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Large, streakier plumage, less obvious head pattern and smaller bill than Beach Stone-curlew. Nocturnal.',
				speciesInflight: 'N\/A',
				speciesSize: '55'},
			{speciesCommon: 'Comb-crested Jacana',
				speciesFirst: 'Comb-crested',
				speciesLast: 'Jacana',
				speciesScientific: 'Irediparra gallinacea',
				speciesImage: 'combcrestedjacana',
				speciesHabitat: 'Tropical freshwater wetlands with abundant floating aquatic vegetation.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Pink-red comb, white face and neck with yellow border, green legs, extremely long toes.',
				speciesInflight: 'N\/A',
				speciesSize: '21'},
			{speciesCommon: 'Common Greenshank',
				speciesFirst: 'Common',
				speciesLast: 'Greenshank',
				speciesScientific: 'Tringa nebularia',
				speciesImage: 'commongreenshank',
				speciesHabitat: 'Coastal intertidal zones and inland saline and freshwater marshes.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Blue-grey two-toned bill appears slightly upturned, and longer and heavier than Marsh Sandpiper. Dark grey upperparts contrasting with white belly; looks very black and white compared with many other waders. Streaky head, long greenish-grey legs (juveniles green), often submerges head completely while feeding.',
				speciesInflight: 'Dark outer, upper wing obvious, and one of the more obvious calls "teu, teu, teu".',
				speciesSize: '33'},
			{speciesCommon: 'Common Redshank',
				speciesFirst: 'Common',
				speciesLast: 'Redshank',
				speciesScientific: 'Tringa totanus',
				speciesImage: 'commonredshank',
				speciesHabitat: 'Mudflats and sandy intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Orange-red legs obvious, and orange-red at base of bill. Overall, looks like a cross between Greenshank and Grey-tailed Tattler, but white trailing edge of secondaries in flight only in Redshank, and white rump extends up to middle of back.',
				speciesInflight: 'N\/A',
				speciesSize: '28'},
			{speciesCommon: 'Common Sandpiper',
				speciesFirst: 'Common',
				speciesLast: 'Sandpiper',
				speciesScientific: 'Actitis hypoleucos',
				speciesImage: 'commonsandpiper',
				speciesHabitat: 'Found singly on rocky or sloped muddy margins of coastal or inland wetlands, including drains, channels and dams - flies low with wings bowed down, bold white wing bar.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'White wedge in front of folded wing is distinctive, olive/bronze upperparts. Bobs tail a lot - tattlers and Wood Sandpipers also bob but generally not as much.',
				speciesInflight: 'Underwing is mostly white with a brown trailing edge, and brown bars across lesser and greater coverts. White wing-bar on upper wing.',
				speciesSize: '20'},
			{speciesCommon: 'Curlew Sandpiper',
				speciesFirst: 'Curlew',
				speciesLast: 'Sandpiper',
				speciesScientific: 'Calidris ferruginea',
				speciesImage: 'curlewsandpiper',
				speciesHabitat: 'Coastal intertidal zones and inland saline and freshwater marshes.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Long down-curved bill. In non-breeding plumage upperparts fairly uniform grey to greyish-brown, with slight supercilium the most obvious area of contrast. Pale whitish underparts, appear very light face-on, plumage varies throughout moulting. Feet and legs black. Often roost with knot spp., Sharp-tailed Sandpiper and Red-necked Stint. Uppers similar to Red Knot if sleeping, though a more slender bird.',
				speciesInflight: 'White rump patch distinctive, with dark tip of tail, white wing bar.',
				speciesSize: '20'},
			{speciesCommon: 'Double-banded Plover',
				speciesFirst: 'Double-banded',
				speciesLast: 'Plover',
				speciesScientific: 'Charadrius bicinctus',
				speciesImage: 'doublebandedplover',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones, also open bare margins of inland freshwater and saline marshes - winter visitor to south-east Australia returning to New Zealand for summer to breed.',
				speciesStatus: 'Winter Migrant',
				speciesTip: 'Supercilium and face are tinged buff in non-breeding plumage. Buff tinge on face fades during winter.<\/p><br \/><p><strong>Compared with Lesser Sand Plover<\/strong> - Bill slighter and shorter, and stands more upright.<\/p><br \/><p><strong>Compared with female or immature Red-capped Plover<\/strong> - Larger, buff tinge to face (though fades) portions of double bar still visible in non-breeding plumage.',
				speciesInflight: 'Dark outer wing, narrow white wing-bar, sides of rump white.',
				speciesSize:'19'}, 
			{speciesCommon: 'Eastern Curlew',
				speciesFirst: 'Eastern',
				speciesLast: 'Curlew',
				speciesScientific: 'Numenius madagascariensis',
				speciesImage: 'easterncurlew',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Largest shorebird, long, curved bill that if turned around could reach rump. Streaky plumage and head.',
				speciesInflight: 'Barred pattern on rump visible.',
				speciesSize: '63'},
			{speciesCommon: 'Greater Sand Plover',
				speciesFirst: 'Greater',
				speciesLast: 'Sand Plover',
				speciesScientific: 'Charadrius leschenaultii',
				speciesImage: 'greatersandplover',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Strong tapered bill, bill length greater than distance from eye to base of bill. Uniform upperparts, white underparts with breast patches that may join.<\/p><br \/><p><strong>Compared with Lesser<\/strong> - Has longer legs, often horizontal posture. Often flat forehaed and tapered look from head to tip of bill. Upperparts paler and feathers often defined by pale fringes.',
				speciesInflight: 'conspicuous broad white wing bar, more white on sides of rump, and toes project beyond the end of tail.',
				speciesSize: '21'}, 
			{speciesCommon: 'Great Knot',
				speciesFirst: 'Great',
				speciesLast: 'Knot',
				speciesScientific: 'Calidris tenuirostris',
				speciesImage: 'greatknot',
				speciesHabitat: 'Coastal mudflats and intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: '<strong>Bill longer than head and sometimes appears to droop, spotted breast<\/strong> (not always obvious), streaky head (more pronounced than in Red Knot), and streaky mantle, nape of neck, and upper-parts. Longer body, and heavy-chested appearance compared to Red Knot, Great Knot has large triangular smudge on lores (area between eye and bill), while Red Knot has a narrower dark marking on lores.',
				speciesInflight: 'Very light wing-bar, white rump (cleaner and whiter than Red Knot - useful for checking flock proportions).',
				speciesSize: '27'},
			{speciesCommon: 'Grey Plover',
				speciesFirst: 'Grey',
				speciesLast: 'Plover',
				speciesScientific: 'Pluvialis squatarola',
				speciesImage: 'greyplover',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Grey upperparts with white speckling, and clean white underparts. Heavily built bird with big head and stout bill. Most Grey Plovers in Australia are females.',
				speciesInflight: 'Black axillaries (underwing near body), white rump patch, and white wing bars distinctive.',
				speciesSize: '29'},
			{speciesCommon: 'Grey-tailed Tattler',
				speciesFirst: 'Grey-tailed',
				speciesLast: 'Tattler',
				speciesScientific: 'Tringa brevipes',
				speciesImage: 'greytailedtattler',
				speciesHabitat: 'Mudflats and sandy intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Horizontal stance, olive yellow legs, otherwise appears featureless, plain grey upperparts aside from white supercilium (eyebrow), also no wing or rump patches, medium-sized straight bill, long wings and tail make rear look narrowly tapered.<\/p><br \/><p><strong>Compared with Wandering Tattler<\/strong> - Very similar, best distinguished by call, supercilium extends past eye, wing tips don\'t extend much past tail, shorter nasal groove, call a 2-3 note whistle.',
				speciesInflight: 'N\/A',
				speciesSize: '25'}, 
			{speciesCommon: 'Hooded Plover',
				speciesFirst: 'Hooded',
				speciesLast: 'Plover',
				speciesScientific: 'Thinornis rubricollis',
				speciesImage: 'hoodedplover',
				speciesHabitat: 'Sandy ocean beaches of southern Australia and open edges of salt lakes in south-west Australia.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Adults have obvious black hood and white nape, upperparts paler and greyer than other plovers. Juveniles look like adults but hood sandy-brown instead of black. Sub-adult head is mottled and darker than on juvenile, big white band on nape separates it clearly from Double-banded Plover.',
				speciesInflight: 'N\/A',
				speciesSize: '21'},
			{speciesCommon: 'Latham\'s Snipe',
				speciesFirst: 'Latham\'s',
				speciesLast: 'Snipe',
				speciesScientific: 'Gallinago hardwickii',
				speciesImage: 'lathamssnipe',
				speciesHabitat: 'Shallow freshwater swamps, erupts from cover with fast zig-zagging flight, eastern Australia.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'This is the only snipe species likely to occur in eastern Australia. In the west there are two other species: Pin-tailed and Swinhoe\'s Snipe, but snipe rarely give you a good look, and even the experts have trouble telling them apart. See "Shorebirds of Australia" and other texts if curious.',
				speciesInflight: 'N\/A',
				speciesSize: '27'}, 
			{speciesCommon: 'Lesser Sand Plover',
				speciesFirst: 'Lesser',
				speciesLast: 'Sand Plover',
				speciesScientific: 'Charadrius mongolus',
				speciesImage: 'lessersandplover',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Shorter blunt bill with bulge often visible toward tip, bill shorter than distance from eye to base of bill. Generally steep forehead.<\/p><br \/><p><strong>Compared with Greater<\/strong> - Darker upperparts often with darker smudge around and below eye, generally darker legs, often stands more upright, has shorter legs and therefore plumper in appearance.',
				speciesInflight: 'Less white visible than Greater, including less white in base of tail and finer wing-bars.',
				speciesSize: '19'},
			{speciesCommon: 'Little Curlew',
				speciesFirst: 'Little',
				speciesLast: 'Curlew',
				speciesScientific: 'Numenius minutus',
				speciesImage: 'littlecurlew',
				speciesHabitat: 'Floodplains and short dry grassland, including lawns and recreational areas of northern Australia.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Bill not much longer than head.<\/p><br \/><p><strong>Compared with Whimbrel<\/strong> - The bill is less curved, while cap and eye-stripe (shorter) are not as pronounced. More buff colouration (warmer upperparts).',
				speciesInflight: 'N\/A',
				speciesSize: '29'},
			{speciesCommon: 'Long-toed Stint',
				speciesFirst: 'Long-toed',
				speciesLast: 'Stint',
				speciesScientific: 'Calidris subminuta',
				speciesImage: 'longtoedstint',
				speciesHabitat: 'Muddy edges of well vegetated freshwater and brackish marshes.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Looks very much like a Stint-sized Sharp-tailed Sandpiper with longer, yellower legs (legs are yellowish green). Bill is finer and sharper, body is more slender, and head is smaller than a Sharp-tailed Sandpiper. Like Pectoral Sandpiper it has clean white under tail coverts. May adopt a hunched crake-like posture, or a very tall posture with long neck especially when alarmed.',
				speciesInflight: 'Thinner wing bar than other stints, and toes extend beyond tail.',
				speciesSize: '14'},
			{speciesCommon: 'Marsh Sandpiper',
				speciesFirst: 'Marsh',
				speciesLast: 'Sandpiper',
				speciesScientific: 'Tringa stagnatilis',
				speciesImage: 'marshsandpiper',
				speciesHabitat: 'Coastal intertidal zones and inland saline and freswater marshes.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Legs olive grey to yellowish, often when feeding will daintily pick at water surface.<\/p><br \/><p><strong>Compared with Greenshank<\/strong> - Fine straight needle like bill is most distinguishing feature of Marsh Sandpiper. It is also noticeably smaller, more delicate and proportionally longer than Greenshank, head often slightly darker, otherwise paler above (plumage often hard to separate between these two).',
				speciesInflight: 'Feet extend well beyond tail. Greenshank feet also extend beyond tail, but not as far. Voice loud "yip", or "phew".',
				speciesSize: '24'},
			{speciesCommon: 'Masked Lapwing',
				speciesFirst: 'Masked',
				speciesLast: 'Lapwing',
				speciesScientific: 'Vanellus miles',
				speciesImage: 'maskedlapwing',
				speciesHabitat: 'Wide variety of short grass habitats, wetland edges and modified urban environments.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Large yellow facial wattles. Absence of black breast-band distinguishes it from Banded Lapwing. Northern race (ssp. <em>miles<\/em>) has larger wattle than eastern race (ssp. <em>novaehollandiae<\/em>). Eastern race has black bars on hindneck extending down sides of chest, lacking in northern race.',
				speciesInflight: 'N\/A',
				speciesSize: '34'},
			{speciesCommon: 'Oriental Plover',
				speciesFirst: 'Oriental',
				speciesLast: 'Plover',
				speciesScientific: 'Charadrius veredus',
				speciesImage: 'orientalplover',
				speciesHabitat: 'Sparsely vegetated plains of arid inland and coastal mudflats and beaches of northern Australia.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Large plover with warm dark brown upperparts, long, pale legs and pale face. Stands tall. Fine head and bill compared to other large plovers.',
				speciesInflight: 'Entire underwing is greyish brown, white belly contrasts with underwing, toes visible beyond tail, dark rump.',
				speciesSize: '25'},
			{speciesCommon: 'Oriental Pratincole',
				speciesFirst: 'Orienatl',
				speciesLast: 'Pratincole',
				speciesScientific: 'Glareola maldivarum',
				speciesImage: 'orientalpratincole',
				speciesHabitat: 'Open and barren grasslands and floodplains of northern Australia.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Larger, stockier, stands more horizontal, with shorter legs than Australian Pratincole. Throat patch on juveniles not as obvious.',
				speciesInflight: 'Very clean white, obvious rump patch and orange\/red wing. Feet don\'t project beyond tail.',
				speciesSize: '24'},
			{speciesCommon: 'Pacific Golden Plover',
				speciesFirst: 'Pacific Golden',
				speciesLast: 'Plover',
				speciesScientific: 'Pluvialis fulva',
				speciesImage: 'pacificgoldenplover',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones, roosting in short saltjmarshes, herb fields or short grass pastures.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Upperparts brown with often obvious golden flecks.<\/p><br \/><p><strong>Compared to Grey Plover<\/strong> - Has more slender and slightly shorter bill, large eye, smaller head, more upright stance, looks smaller, lankier.',
				speciesInflight: 'Uniformly coloured underwing, lacks white wing bar on upper-wing.',
				speciesSize: '25'},
			{speciesCommon: 'Pectoral Sandpiper',
				speciesFirst: 'Pectoral',
				speciesLast: 'Sandpiper',
				speciesScientific: 'Calidris melanotos',
				speciesImage: 'pectoralsandpiper',
				speciesHabitat: 'Coastal and inland saline or freshwater marshes.',
				speciesStatus: 'Summer Migrant',
				speciesTip: '<strong>Compared with Sharp-tailed Sandpiper<\/strong> - Longer bill, yellowish tinge at base of bill much more pronounced, clean white under-tail coverts, lack rusty crown (but so do many Sharpies), sharp demarcation between streaked breast and white belly (Sharpies can look a bit like this, so while it is generally much clearer in Pectoral, it is not enough to be sure of identification - breast streaking tends to extend down the sides in Sharpies). Also, supercilium is broader in front of eye.',
				speciesInflight: 'N\/A',
				speciesSize: '21'},
			{speciesCommon: 'Red-capped Plover',
				speciesFirst: 'Red-capped',
				speciesLast: 'Plover',
				speciesScientific: 'Charadrius ruficapillus',
				speciesImage: 'redcappedplover',
				speciesHabitat: 'Bare mudflats and margins of inland and coastal saline wetlands.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Smallest Australian plover, with the shortest and finest bill of any Australian plover. Adult males have distinctive red cap and black bar on side of breast. Adult females are paler, more similar to immature birds.<\/p><br \/><p><strong>Compared with Double-banded Plover<\/strong> - Immature and female Red-capped Plovers lack buff on face, have paler upperparts, supercilium is shorter and breast is often paler.',
				speciesInflight: 'More white on sides of tail than Double-banded Plover.',
				speciesSize: '15'},
			{speciesCommon: 'Red-kneed Dotterel',
				speciesFirst: 'Red-kneed',
				speciesLast: 'Dotterel',
				speciesScientific: 'Erythrogonys cinctus',
				speciesImage: 'redkneeddotterel',
				speciesHabitat: 'Feeds in shallow margins of inland freshwater wetlands, including temporary shallows after rain.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Black hood and chest band, red flanks.',
				speciesInflight: 'N\/A',
				speciesSize: '18'},
			{speciesCommon: 'Red Knot',
				speciesFirst: 'Red',
				speciesLast: 'Knot',
				speciesScientific: 'Calidris canutus',
				speciesImage: 'redknot',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: '<strong>Bill length similar to head length, chevron marks on flanks and breast<\/strong>, plain mantle, slight streaking on head (less streaked than Great Knot) with plain nape of neck and mantle, and relatively smooth grey back, eyebrow often the point of most obvious contrast on upperparts, generally more contrast between upperparts and belly than in Great Knot, breast can be spotted, line from bill to eye can appear more obvious. Smaller than Great Knot and dumpy looking.',
				speciesInflight: 'Rump with light barring, narrow wing bar.',
				speciesSize: '24'},
			{speciesCommon: 'Red-necked Avocet',
				speciesFirst: 'Red-necked',
				speciesLast: 'Avocet',
				speciesScientific: 'Recurvirostra novaehollandiae',
				speciesImage: 'redneckedavocet',
				speciesHabitat: 'Saline lakes and saltpans but also a variety of freshwater wetlands and coastal intertidal zones.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Long, slender up-turned bill and chestnut head & neck. Feeds in shallow water rapidly sweeping bill from side to side.',
				speciesInflight: 'N\/A',
				speciesSize: '44'},
			{speciesCommon: 'Red-necked Stint',
				speciesFirst: 'Red-necked',
				speciesLast: 'Stint',
				speciesScientific: 'Calidris ruficollis',
				speciesImage: 'redneckedstint',
				speciesHabitat: 'Coastal intertidal zones and inland saline and freshwater marshes.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Smallest, most common shorebird in Australia; dumpy with short legs and bill (both black), streaked head, grey to greyish brown upperparts, white below, back streaky looking as feathers often have dark centres.<\/p><br \/><p><strong>Compared to Sanderling<\/strong> - Upperparts darker and Sanderling generally lack slight dark line from bill through eye.',
				speciesInflight: 'White wing bar across primaries, black centre to rump and tail with white outer tail.',
				speciesSize: '14'},
			{speciesCommon: 'Ruddy Turnstone',
				speciesFirst: 'Ruddy',
				speciesLast: 'Turnstone',
				speciesScientific: 'Arenaria interpres',
				speciesImage: 'ruddyturnstone',
				speciesHabitat: 'Sandy or cobble beaches, rock platforms and reefs of coastal Australia.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Bright orange legs, wedge-shaped bill, distinctive brown-black breast, warm upperparts, white underparts. "Tubby" appearance with a horizontal stance.',
				speciesInflight: 'White rump.',
				speciesSize: '23'}, 
			{speciesCommon: 'Sanderling',
				speciesFirst: '',
				speciesLast: 'Sanderling',
				speciesScientific: 'Calidris alba',
				speciesImage: 'sanderling',
				speciesHabitat: 'Exposed sandy ocean beaches where tight feeding groups run quickly along edge of surf, also sandbars and mudflats.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Bright white underparts, very grey upperparts, often notable white about the head, only three toes. Very active feeders, run after retreating waves.<\/p><br \/><p><strong>Compared to Red-necked Stint<\/strong> - Feathers on upperparts have more white fringing, lack hind tail, heavier and longer bill; Stint have darker upper parts and are 25% smaller. Sanderling generally lacks the somewhat pronounced slight dark line from bill through eye.',
				speciesInflight: 'Wide white wing bar.',
				speciesSize: '21'},
			{speciesCommon: 'Sharp-tailed Sandpiper',
				speciesFirst: 'Sharp-tailed',
				speciesLast: 'Sandpiper',
				speciesScientific: 'Calidris acuminata',
				speciesImage: 'sharptailedsandpiper',
				speciesHabitat: 'Coastal intertidal zones and inland saline and freshwater marshes',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Boldly streaked and mottled in shades of dark and light brown (varies widely), marked on breast and flanks. Often rusty ginger crown (more so on juveniles), green-yellow legs, and legs usually slightly bent. Streaking on under-tail coverts and breast, usually distinct eyebrow, and usually slight droop in bill.',
				speciesInflight: 'Less white on outer tail feathers, and finer wing-bars than Red-necked Stint.',
				speciesSize: '20'}, 
			{speciesCommon: 'Sooty Oystercatcher',
				speciesFirst: 'Sooty',
				speciesLast: 'Oystercatcher',
				speciesScientific: 'Haematopus fuliginosus',
				speciesImage: 'sootyoystercatcher',
				speciesHabitat: 'Coastal rock platforms and rocky islets.',
				speciesStatus: 'Resident Species',
				speciesTip: 'Distinctive all-black plumage with red bill and pink legs. Stocky appearance.',
				speciesInflight: 'N\/A',
				speciesSize: '46'}, 
			{speciesCommon: 'Terek Sandpiper',
				speciesFirst: 'Terek',
				speciesLast: 'Sandpiper',
				speciesScientific: 'Xenus cinereus',
				speciesImage: 'tereksandpiper',
				speciesHabitat: 'Exposed intertidal zones, energetically hunts mobile prey primarily small crabs.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Distinctive upturned bill with orange base, and orange to yellow orange legs obvious, generally brighter than Tattler. Very steep forehead, upperparts plain grey but with black streaks on scapulars (never seen on Tattlers), contrast between wings and belly strong, and usually dark primaries and tail make rear contrast with the rest of upper parts.',
				speciesInflight: 'N\/A',
				speciesSize: '23'},
			{speciesCommon: 'Wandering Tattler',
				speciesFirst: 'Wandering',
				speciesLast: 'Tattler',
				speciesScientific: 'Tringa incana',
				speciesImage: 'wanderingtattler',
				speciesHabitat: 'Rocky coasts and reefs, mainly Queensland and northern NSW.',
				speciesStatus: 'Summer Migrant',
				speciesTip: '<strong>Compared with Grey-tailed Tattler<\/strong> - Heavier bill with longer nasal groove, darker grey upperparts, smaller white eyebrow that does not meet on forehead and rarely extends beyond eye, wing tips usually extend beyond tail. In breeding plumage underparts more heavily barred dark grey. Call a rippling trill.',
				speciesInflight: 'N\/A',
				speciesSize: '25'},
			{speciesCommon: 'Whimbrel',
				speciesFirst: '',
				speciesLast: 'Whimbrel',
				speciesScientific: 'Numenius phaeopus',
				speciesImage: 'whimbrel',
				speciesHabitat: 'Coastal mudflats and sandy intertidal zones.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'Noticeably smaller than Eastern Curlew, bill if turned around would only reach its middle back. Noticeable striped head and crown, dirty white eyebrow, barred flanks, pale to white upper rump. Generally short and dumpy bird.',
				speciesInflight: 'Rump wedge-shaped and much paler than Eastern Curlew.',
				speciesSize: '42'},
			{speciesCommon: 'Wood Sandpiper',
				speciesLast: 'Sandpiper',
				speciesScientific: 'Tringa glareola',
				speciesImage: 'woodsandpiper',
				speciesHabitat: 'Shallow freshwater marshes with abundant aquatic vegetation.',
				speciesStatus: 'Summer Migrant',
				speciesTip: 'White spotted upperparts are the most obvious unique feature. Smallish sandpiper, with conspicuous supercilium, long greenish-yellow to olive-brown legs, squared white rump above dark barred tail, and whitish eye-ring. Lankier and taller than Sharp-tailed Sandpiper, shorter bill than Marsh Sandpiper. Breast streaking is often heavy.',
				speciesInflight: 'N\/A',
				speciesSize: '21'}
        ]
    }
});